server:
  port: ${PORT:8081}
spring:
  application:
    name: auth-service
jwt:
  private-key: ${JWT_PRIVATE_KEY_BASE64}
  public-key: ${JWT_PUBLIC_KEY_BASE64}
  algorithm: ${JWT_ALGORITHM:RS256}
  expiration: ${JWT_EXPIRATION:3600000}
  issuer: ${JWT_ISSUER:mytruyen-auth}
  audience: ${JWT_AUDIENCE:mytruyen-api}

logging:
  level:
    org.springframework.security: DEBUG

user:
  service:
    url: ${USER_SERVICE_URL:http://localhost:8082}

app:
  intern-api-key: ${internal-api-key:mytruyen}
