server:
  port: ${PORT:8081}
spring:
  application:
    name: auth-service
#  datasource:
#    url: ${DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

jwt:
  secret: ${JWT_SECRET:vLs5M1qfI62y7Q00LBuHNHpELYqau7lBVjt9yQlz5tM=}
  algorithm: ${JWT_ALGORITHM:HS256}
  expiration: ${JWT_EXPIRATION:360000000}

logging:
  level:
    org.springframework.security: DEBUG

user:
  service:
    url: ${USER_SERVICE_URL:http://localhost:8082}