server:
  port: ${PORT:8081}
spring:
  application:
    name: auth-service
jwt:
  secret: ${JWT_SECRET}
  algorithm: ${JWT_ALGORITHM:HS256}
  expiration: ${JWT_EXPIRATION:3600000}
  issuer: ${JWT_ISSUER:mytruyen-auth}
  audience: ${JWT_AUDIENCE:mytruyen-api}

logging:
  level:
    org.springframework.security: DEBUG

user:
  service:
    url: ${USER_SERVICE_URL:http://localhost:8082}
