CREATE TABLE authors (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    local_name VARCHAR(255),
    avatar_url TEXT,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX ix_authors_name ON authors(name);

CREATE TABLE book_statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE genres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(150) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(150) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    type VARCHAR(50) NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX ix_tags_type ON tags(type, id);

CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id UUID REFERENCES authors(id),
    creator_id UUID NOT NULL,
    status_id BIGINT NOT NULL REFERENCES book_statuses(id),
    name VARCHAR(500) NOT NULL,
    slug VARCHAR(500) NOT NULL UNIQUE,
    kind INTEGER NOT NULL,
    sex INTEGER NOT NULL,
    synopsis TEXT NOT NULL,
    poster JSONB,
    note TEXT,
    chapter_per_week INTEGER NOT NULL DEFAULT 0 CHECK (chapter_per_week >= 0),
    published BOOLEAN NOT NULL DEFAULT FALSE,
    published_at TIMESTAMP WITH TIME ZONE,
    deleted_at TIMESTAMP WITH TIME ZONE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX ix_books_author ON books(author_id);
CREATE INDEX ix_books_creator ON books(creator_id);
CREATE INDEX ix_books_status ON books(status_id);
CREATE INDEX ix_books_public ON books(published, deleted_at, published_at DESC, id DESC);

CREATE TABLE book_genres (
    book_id BIGINT NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    genre_id BIGINT NOT NULL REFERENCES genres(id),
    PRIMARY KEY (book_id, genre_id)
);
CREATE INDEX ix_book_genres_genre ON book_genres(genre_id, book_id);
CREATE TABLE book_tags (
    book_id BIGINT NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    tag_id BIGINT NOT NULL REFERENCES tags(id),
    PRIMARY KEY (book_id, tag_id)
);
CREATE INDEX ix_book_tags_tag ON book_tags(tag_id, book_id);

CREATE TABLE chapters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    creator_id UUID NOT NULL,
    chapter_index INTEGER NOT NULL CHECK (chapter_index > 0),
    name VARCHAR(500) NOT NULL,
    word_count BIGINT NOT NULL DEFAULT 0 CHECK (word_count >= 0),
    published BOOLEAN NOT NULL DEFAULT FALSE,
    published_at TIMESTAMP WITH TIME ZONE,
    deleted_at TIMESTAMP WITH TIME ZONE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_chapters_book_index UNIQUE (book_id, chapter_index)
);
CREATE INDEX ix_chapters_public ON chapters(book_id, published, deleted_at, chapter_index);
CREATE INDEX ix_chapters_creator ON chapters(creator_id);
CREATE TABLE chapter_contents (
    chapter_id BIGINT PRIMARY KEY REFERENCES chapters(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    content_hash VARCHAR(64) NOT NULL CHECK (char_length(content_hash) = 64),
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE book_content_stats (
    book_id BIGINT PRIMARY KEY REFERENCES books(id) ON DELETE CASCADE,
    chapter_count BIGINT NOT NULL DEFAULT 0 CHECK (chapter_count >= 0),
    word_count BIGINT NOT NULL DEFAULT 0 CHECK (word_count >= 0),
    latest_chapter_index INTEGER CHECK (latest_chapter_index > 0),
    new_chap_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX ix_content_stats_new_chapter ON book_content_stats(new_chap_at DESC, book_id DESC);
CREATE TABLE book_engagement_projection (
    book_id BIGINT PRIMARY KEY REFERENCES books(id) ON DELETE CASCADE,
    view_count BIGINT NOT NULL DEFAULT 0 CHECK (view_count >= 0),
    comment_count BIGINT NOT NULL DEFAULT 0 CHECK (comment_count >= 0),
    review_count BIGINT NOT NULL DEFAULT 0 CHECK (review_count >= 0),
    rating_sum BIGINT NOT NULL DEFAULT 0 CHECK (rating_sum >= 0),
    bookmark_count BIGINT NOT NULL DEFAULT 0 CHECK (bookmark_count >= 0),
    source_version BIGINT NOT NULL DEFAULT 0 CHECK (source_version >= 0),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
