server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${AUTH_SERVICE_URI:http://localhost:8081}
              predicates:
                - Path=/api/v1/auth/**
            - id: user-service
              uri: ${USER_SERVICE_URI:http://localhost:8082}
              predicates:
                - Path=/api/v1/users/**
            - id: book-service
              uri: ${BOOK_SERVICE_URI:http://localhost:8000}
              predicates:
                - Path=/api/**
          cors:
            allowed-origins: "*"
            allowed-methods: "*"
eureka:
  client:
    enabled: false

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    reactor.netty.http.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
    secret: ${JWT_SECRET:vLs5M1qfI62y7Q00LBuHNHpELYqau7lBVjt9yQlz5tM=}
    algorithm: ${JWT_ALGORITHM:HS256}
    expiration: ${JWT_EXPIRATION:8640000000}