server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/users/**
              filters:
                - StripPrefix=1
            - id: fastapi
              uri: http://localhost:8000
              predicates:
                - Path=/api/**
          cors:
            allowed-origins: "*"
            allowed-methods: "*"
eureka:
  client:
    enabled: false

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    reactor.netty.http.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"