server:
    port: ${PORT:8082}
spring:
  application:
    name: user-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  public-key: ${JWT_PUBLIC_KEY_BASE64}
  algorithm: ${JWT_ALGORITHM:RS256}
  issuer: ${JWT_ISSUER:mytruyen-auth}
  audience: ${JWT_AUDIENCE:mytruyen-api}

logging:
  level:
    org.springframework.security: DEBUG

app:
  admin:
    enabled: ${BOOTSTRAP_ADMIN_ENABLED:false}
    email: ${BOOTSTRAP_ADMIN_EMAIL:}
    username: ${BOOTSTRAP_ADMIN_USERNAME:}
    password: ${BOOTSTRAP_ADMIN_PASSWORD:}
  internal-api-key: ${INTERNAL_API_KEY}
