"""add index for chapter

Revision ID: aa6f3fcc8ac5
Revises: a46baa154e17
Create Date: 2026-03-08 11:30:22.581206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'aa6f3fcc8ac5'
down_revision: Union[str, Sequence[str], None] = 'a46baa154e17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_chapter_book_index', 'chapter', ['book_id', 'index'], unique=False)
    op.create_unique_constraint('uq_chapter_book_index', 'chapter', ['book_id', 'index'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_chapter_book_index', 'chapter', type_='unique')
    op.drop_index('idx_chapter_book_index', table_name='chapter')
    # ### end Alembic commands ###
